[[redirects]]
  from = "https://easycase.fr/*"
  to = "https://eazycase.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.easycase.fr/*"
  to = "https://eazycase.fr/:splat"
  status = 301
  force = true
